name: ansaap_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.7
  form_validator:
    git: https://github.com/themisir/form-validator.git
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  skeletonizer: ^1.4.1+1
  freezed_annotation: ^2.4.4
  intl: any
  dio: ^5.7.0
  connectivity_plus: ^6.1.0
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  pretty_bloc_observer: ^1.0.4
  get_it: ^8.0.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  freezed: ^2.5.7
  injectable: ^2.5.0
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.2
  qr_code_scanner: ^1.0.1
  scan: ^1.6.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  image_network: ^2.5.6
  pretty_dio_logger: ^1.4.0
  loading_indicator: ^3.1.1
  auto_route: ^9.2.2
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.2.0+3
  pin_code_fields: ^8.0.1
  flashy_tab_bar2: ^0.0.10
  icons_plus: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:
  build_runner: ^2.4.6
  dependency_validator: ^4.1.2
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  awesome_snackbar_content:
    git:
      url: https://github.com/aleemElmozogi/awesome_snackbar_content.git
      ref: fix/bubble-icon-cropping
  auto_route_generator:
  flutter_form_builder: ^9.5.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logo/
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
assets/icons/tree:
  svg:flutter_intl:
  enabled: true
